tour:
  @cat src/lib.rs

build:
  wasm-pack build --release

_quiet-build:
  wasm-pack build --release 2> /dev/null

inspect: _quiet-build
  wasm2wat pkg/fibonacci_bg.wasm

test: _quiet-build
  node test.js

doc:
  @google-chrome https://webassembly.github.io/spec/core/syntax/instructions.html
