tour:
  @cat src/lib.rs

build:
  wasm-pack build --release --target=nodejs

_quiet-build:
  wasm-pack build --release --target=nodejs 2> /dev/null

inspect: _quiet-build
  wasm2wat pkg/time_bg.wasm | less

test: _quiet-build
  node test.js

build-heavy:
  cargo build --release --target=wasm32-wasi

show-heavy: build-heavy
  ls -lh target/wasm32-wasi/release/
