[package]
name = "protos"
version = "0.1.0"
authors = ["Ryan Brewster <ryanpbrewster@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
prost = "0.7"
wasmtime = "0.26"

[build-dependencies]
anyhow = "1.0"
prost-build = "0.7"
