[package]
name = "parser"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "6.0"
wasm-bindgen = "0.2"
wee_alloc = "0.4.5"

[profile.release]
opt-level = "s"
