tour:
  @cat src/lib.rs

build:
  wasm-pack build --release --target=nodejs

_quiet-build:
  wasm-pack build --release --target=nodejs 2> /dev/null

inspect: _quiet-build
  wasm2wat pkg/reverse_bg.wasm | less

test: _quiet-build
  node test.js

tiny:
  cp .tiny/Cargo.toml Cargo.toml
  cp .tiny/lib.rs src/lib.rs

prep: build
